🤖 add job to detect msrv changes

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -29,6 +29,22 @@ jobs:
           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
       - uses: clechasseur/rs-clippy-check@v3
 
+  msrv:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - run: |
+          cargo_msrv="cargo-msrv-x86_64-unknown-linux-gnu-v0.16.0-beta.22"
+          curl -SLo $cargo_msrv.tgz https://github.com/foresterre/cargo-msrv/releases/download/v0.16.0-beta.22/$cargo_msrv.tgz
+          tar -xvf $cargo_msrv.tgz
+          mv $cargo_msrv/cargo-msrv ./
+          defined_msrv=$(./cargo-msrv show --output-format json 2>&1 | jq -r '.result.version' | tail -n 1)
+          dependency_msrv=$(./cargo-msrv list --output-format json 2>&1 | jq -r '.result.list.[0].msrv' | tail -n 1)
+          if [ $defined_msrv != $dependency_msrv ]; then
+            echo "::error::MSRV changed - current: '$defined_msrv', absolute: '$dependency_msrv'"
+            exit 1
+          fi
+
   actionlint:
     runs-on: ubuntu-latest
     steps:
