🤖 add lint job to detect MSRV changes (#324)

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -29,6 +29,31 @@ jobs:
           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
       - uses: clechasseur/rs-clippy-check@v3
 
+  msrv:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Setup dependencies
+        run: |
+          # Setup latest jq
+          curl -Lo jq https://github.com/jqlang/jq/releases/latest/download/jq-linux-amd64
+          chmod +x jq
+          # Setup cargo msrv
+          cargo_msrv="cargo-msrv-x86_64-unknown-linux-gnu-v0.16.0-beta.22"
+          curl -Lo "$cargo_msrv".tgz https://github.com/foresterre/cargo-msrv/releases/download/v0.16.0-beta.22/"$cargo_msrv".tgz
+          tar -xvf "$cargo_msrv".tgz
+          mv "$cargo_msrv"/cargo-msrv ./
+      - name: Detect MSRV changes
+        run: |
+          defined_msrv="$(./cargo-msrv show --output-format json 2>&1 | ./jq -r '.result.version' | tail -n 1)"
+          dependency_msrv="$(./cargo-msrv list --output-format json 2>&1 | ./jq -r '.result.list.[0].msrv' | tail -n 1)"
+          echo "defined_msrv=$defined_msrv"
+          echo "dependency_msrv=$dependency_msrv"
+          if [ "$defined_msrv" != "$dependency_msrv" ]; then
+            echo "::error::MSRV changed | defined: '$defined_msrv', absolute: '$dependency_msrv'"
+            exit 1
+          fi
+
   actionlint:
     runs-on: ubuntu-latest
     steps:
